#ifndef ERROR_PARSER_H_INCLUDED
#define ERROR_PARSER_H_INCLUDED

enum ErrorCodes
{
    FILE_NULL_POINTER = -15,
    NULL_KEY_POINTER,
    NULL_HASH_TABLE_POINTER,
    BUFFER_NULL_POINTER,
    FREAD_ERROR,
    ALLOCATION_FAILURE,
    UNEXPECTED_BEHAVIOUR,
    KEY_IS_TOO_BIG,
    NO_KEY_TO_DELETE,
    HASH_FUNCTION_NULL_POINTER,
    MISSALIGNMENT,
    MODULE_SUCCESS = 0,
};

void ParseError(enum ErrorCodes code);

#endif // ERROR_PARSER_H_INCLUDED